// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerLinesAccuracyService.Data;

namespace PowerLinesAccuracyService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200607183450_AddAccuracy")]
    partial class AddAccuracy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PowerLinesAccuracyService.Models.Accuracy", b =>
                {
                    b.Property<int>("AccuracyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("accuracyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Calculated")
                        .HasColumnName("calculated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Division")
                        .HasColumnName("division")
                        .HasColumnType("text");

                    b.Property<int>("LowerRecommended")
                        .HasColumnName("lowerRecommended")
                        .HasColumnType("integer");

                    b.Property<decimal>("LowerRecommendedAccuracy")
                        .HasColumnName("lowerRecommendedAccuracy")
                        .HasColumnType("numeric");

                    b.Property<int>("Matches")
                        .HasColumnName("matches")
                        .HasColumnType("integer");

                    b.Property<int>("Recommended")
                        .HasColumnName("recommended")
                        .HasColumnType("integer");

                    b.Property<decimal>("RecommendedAccuracy")
                        .HasColumnName("recommendedAccuracy")
                        .HasColumnType("numeric");

                    b.HasKey("AccuracyId");

                    b.ToTable("accuracy");
                });
#pragma warning restore 612, 618
        }
    }
}
