services:
  power-lines-accuracy-service:
    build:
      target: development
    depends_on: 
      - power-lines-message
      - power-lines-accuracy-service-postgres
    entrypoint: >
      sh -c "
        scripts/wait-for.sh power-lines-message:5672 --
        scripts/wait-for.sh power-lines-accuracy-service-postgres:6001 --
        dotnet watch --project ./PowerLinesAccuracyService run"
    ports:
      - "5001:5001"
    environment:
      ConnectionStrings__PowerLinesAccuracyService: "Server=power-lines-accuracy-service-postgres;Port=5432;Database=power_lines_accuracy;User Id=postgres;Password=postgres;"
      Message__Host: power-lines-message
      AnalysisUrl__Endpoint: http://power-lines-analysis-service:5003
    volumes:
      - ./PowerLinesAccuracyService:/home/dotnet/PowerLinesAccuracyService
      - ./PowerLinesAccuracyService.Tests:/home/dotnet/PowerLinesAccuracyService.Tests
      - ./scripts:/home/dotnet/scripts

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

  power-lines-accuracy-service-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: power_lines_accuracy
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

networks:
  power-lines:
    driver: bridge
    name: power-lines
