environment: production
name: power-lines-accuracy-service
image: power-lines-accuracy-service

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 350Mi
  limitCpu: 250m
  port: 5001
  comPlusEnableDiagnostics: 0
  analysisEndpoint: http://power-lines-analysis-service

message:
  host: services.lynxmagnus.com
  port: 5672
  analysisQueue: power-lines-analysis
  resultQueue: power-lines-results
  resultSubscription: power-lines-results-accuracy
  oddsQueue: power-lines-odds
  oddsSubscription: power-lines-odds-accuracy

deployment: {}
