container:
  image: power-lines-accuracy-service
  resourceTier: L
  port: 5001
  comPlusEnableDiagnostics: 0

configMap:
  environment: production
  analysisEndpoint: http://power-lines-analysis-service

message:
  host: services.lynxmagnus.com
  port: 5672
  analysisQueue: power-lines-analysis
  resultQueue: power-lines-results
  resultSubscription: power-lines-results-accuracy
  oddsQueue: power-lines-odds
  oddsSubscription: power-lines-odds-accuracy

deployment: {}

secret:
  secretsPath: /power-lines-accuracy-service
