name: power-lines-accuracy-service
image: power-lines-accuracy-service

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 350Mi
  limitCpu: 250m
  port: 5001
  comPlusEnableDiagnostics: 0
  connectionString: "User Id=postgres;Password=postgres;Server=power-lines-accuracy-service-postgres;Port=5432;Database=Database=power_lines_accuracy;"
  analysisEndpoint: http://power-lines-analysis-service

message:
  host: host.docker.internal
  port: 5672
  username: rabbitmq
  password: rabbitmq
  analysisQueue: power-lines-analysis
  resultQueue: power-lines-results
  resultSubscription: power-lines-results-accuracy
  oddsQueue: power-lines-odds
  oddsSubscription: power-lines-odds-accuracy

deployment: {}
